[package]
name = "lan-pam"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9"
openssl = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
tokio = { version = "1.48", features = ["macros", "rt", "io-util", "time", "net"] }
futures = "0.3"
